name: json_data_explorer
description: A highly customizable widget to render and interact with JSON objects.
version: 0.1.1
repository: https://github.com/rows/json_data_explorer
homepage: https://github.com/rows/json_data_explorer
issue_tracker: https://github.com/rows/json_data_explorer/issues

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.5
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  rows_lint: 0.1.0
  mocktail: ^0.3.0
  golden_toolkit: ^0.13.0

flutter:
  uses-material-design: true